accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
        path("signup/", SignUpView.as_view(), name="signup"),
        ]

articles/urls.py
from django.urls import path

from .views import (
        ArticleListView,
        ArticleDetailView,
        ArticleUpdateView,
        ArticleDeleteView,
        ArticleCreateView,
        )


urlpatterns = [
        path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
        path("<int:pk>/edit/", ArticleUpdateView.as_view(), name="article_edit"),
        path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
        path("new/", ArticleCreateView.as_view(), name="article_new"),
        path("", ArticleListView.as_view(), name="article_list"),
        ]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView


urlpatterns = [
        path("", HomePageView.as_view(), name="home"),
        ]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE,
            )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE,
            )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
                "username",
                "email",
                "age",
                )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
                "username",
                "email",
                "age",
                )

articles/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy, reverse

from .models import Article
from .forms import CommentForm


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "article_list.html"


class CommentGet(DetailView):
    model = Article
    template_name = "article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.object
        return reverse("article_detail", kwargs={"pk": article.pk})


class ArticleDetailView(LoginRequiredMixin, DetailView):
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ("title", "body",)
    template_name = "article_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = "article_delete.html"
    success_url = reverse_lazy("article_list")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "article_new.html"
    fields = ("title", "body",)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

templates/article_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ article.title }}"?</p>
  <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="article-entry">
  <h2>{{ object.title }}</h2>
  <p>by {{ object.author }} | {{ object.date }}</p>
  <p>{{ object.body }}</p>
</div>

<hr>
<h4>Comments</h4>
{% for comment in article.comment_set.all %}
<p>{{ comment.author }} &middot; {{ comment }}</p>
{% endfor %}
<hr>

<h4>Add a comment</h4>
<form action="" method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success ml-2">Save</button>
</form>
<br>

<div>
  {% if article.author.pk == request.user.pk %}
    <p><a href="{% url 'article_edit' article.pk %}">Edit</a>
    <a href="{% url 'article_delete' article.pk %}">Delete</a>
    </p>
  {% endif %}
  <p>Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>
</div>

{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/article_list.html
{% extends "base.html" %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for article in article_list %}
<div class="card">
  <div class="card-header">
    <span class="fw-bold">
      <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
    </span> &middot;
    <span class="text-muted">by {{ article.author }} |
      {{ article.date }}</span>
  </div>
  <div class="card-body">
    <p>{{ article.body }}</p>
    {% if article.author.pk == request.user.pk %}
      <a href="{% url 'article_edit' article.pk %}">Edit</a>
      <a href="{% url 'article_delete' article.pk %}">Delete</a>
    {% endif %}
    <a href="{{ article.get_absolute_url }}">New Comment</a>
  </div>
  <div class="card-footer text-left text-muted">
    {% for comment in article.comment_set.all %}
    <p>
    <span class="fw-bold">
      {{ comment.author }} &middot;
    </span>
    {{ comment }}
    </p>
    {% endfor %}
  </div>
</div>
<br />
{% endfor %}
{% endblock content %}

templates/article_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h1>New Article</h1>
<form action="" method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success ml-2" type="submit">Save</button>
</form>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Nespaper App{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<head>
<body class="px-3">
  <header class="p-3 mb-3 border-bottom">
    <div class="d-flex flex-wrap align-items-center justify-content-center
      justify-content-lg-start">
      <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
        mb-md-0">
      {% if user.is_authenticated %}
        <li><a href="{% url 'article_new' %}" class="nav-link px2 link-dark">+ New</a></li>
      </ul>
      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
          id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          {{ user.username }}
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="{% url 'password_change' %}">
            Change password</a></li>
          <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
        </ul>
      </div>
      {% else %}
      </ul>
      <div class="text-end">
        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
          Log In</a>
        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
      </div>
      {% endif %}
    </div>
  </div>
  </header>
  <main>
    {% block content %}
    {% endblock content %}
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}
<p>Hi {{ user.username|title }}! Your age is {{ user.age }}</p>
<p><a href="{% url 'logout' %}">Log Out</a></p>
<p><a class="btn btn-primary btn-lg" href="{% url 'article_list' %}" role="button">View all articles</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a> |
<a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock content %}